### ISSUE TITLE
Small issue breaking my theme

### ISSUE THREAD

**Issue by Norwayman** [e107inc/youtube#1]
Trying out this fresh plugin. NICE!
I have one thing first of all:
When I click the Youtube menu button it breaks my theme like so:

![01_breaking theme borders](https://cloud.githubusercontent.com/assets/1757346/19819236/54d02454-9d19-11e6-9875-3b8ca320283d.PNG)

What would be the reason for this?

Then when I click the link on the folling page it all appears great like so:

![02_chanelvideoes_fine](https://cloud.githubusercontent.com/assets/1757346/19819271/7873c370-9d19-11e6-9c16-64fa4ec5d0a3.PNG)

**Comment by CaMer0n** [comment]
Thanks. I'll look into it.

**Comment by CaMer0n** [comment]
@Norwayman Please give it another try. Thanks.

**Comment by Norwayman** [comment]
@CaMer0n It works gret with the margin of the theme now.
But....in the heading it shows LAN_YOUTUBE_004

UPDATE:  Oops....sorry....I had forgotten to copy the language files also to my directories of Spanish and Norwegian.

![workinggreatnow](https://cloud.githubusercontent.com/assets/1757346/19904522/92848480-a038-11e6-812e-a8cf0254aacb.JPG)
