### ISSUE TITLE
"Type" field in plugin's admin panel dead because admin_config.php missing it's writeParms...

### ISSUE THREAD

**Issue by HatchlingByHeart** [e107inc/youtube#11]
I've tried repeatedly to use this plugin only to find that only usernames worked in the Ref field, and also noticed the Type field in the Youtube plugin's admin panel was always blank.

I examined admin_config.php and found that inserting "array(0 => 'User', 1 => 'Channel', 2 => 'Playlist')" into the type field's writeParms corrected the issue and made the menu work again, and channel and playlist IDs also work now.

For anyone else having this issue, try this, and I hope Cameron will update this plugin to include this fix.

**Comment by Moc** [comment]
Thanks! Pull requests are welcome! :)

**Comment by HatchlingByHeart** [comment]
> 
> 
> Thanks! Pull requests are welcome! :)

Pull request has been made. Thank you.

**Comment by Jimmi08** [comment]
@Moc latest github is working, this can be closed 

![image](https://user-images.githubusercontent.com/5429548/151393762-500024d5-b55c-4e1c-af15-1f88083d4288.png)
