### ISSUE TITLE
How to work this plugin?

### ISSUE THREAD

**Issue by yesszus** [e107inc/youtube#3]
I have YouTube API key.
Tutorial?
All data is completed and I see a blank page.

![image](https://cloud.githubusercontent.com/assets/17430115/19889333/9c3b2fdc-a034-11e6-9f4a-7ac12fc5e5cb.png)

**Comment by CaMer0n** [comment]
Please enable DEBUG in "basic" mode. It should display the feed URL in the footer which you can paste into your browser to check that the feed is working.

**Comment by yesszus** [comment]
Solved!
Node.js Online  conflict this plugin.

**Comment by CaMer0n** [comment]
@lonalore

**Comment by lonalore** [comment]
@yesszus What kind of error message do you see on the console? Can I see it somewhere?

**Comment by yesszus** [comment]
Test site

[url=http://e107.totalh.net/videos]e107.totalh.net[/url]

**Comment by yesszus** [comment]
Test site

[http://e107.totalh.net/videos](url)

**Comment by yesszus** [comment]
Test site

[](http://e107.totalh.net/videos)

**Comment by yesszus** [comment]
Test site:  http://e107.totalh.net/videos

Updated Node.js latest version 1.3 and not conflict this plugin.

**Comment by lonalore** [comment]
Okay.
Just for note: it seems that Node.js plugin is not configured properly. Do you have installed Node.js on your server? But this does not belong to this issue... :)

**Comment by Moc** [comment]
Closing this. For further discussion on this plugin conflict: https://github.com/lonalore/nodejs

**Comment by Moc** [comment]
Turns out I cannot close it, yay. 

@CaMer0n Can you check my permissions for this repo please? Gracias

**Comment by CaMer0n** [comment]
@Moc fixed! Thanks
